### ISSUE TITLE
Assertion

### ISSUE THREAD

**Issue by gerritgr** [fabridamicelli/kuramoto#1]
Hi, great work. It is exactly what I was just looking for.
But I think you have a typo in the assertion "assert n_nodes is not None and natfreqs is not None" => should probably be an "or".  Also, with Python3 and current numpy, I had to convert the 3rd parameter of linspace to int explicitly ("np.linspace(0, self.T, int(self.T/self.dt))") to make it run.

**Comment by fabridamicelli** [comment]
Hi @gerritgr ! Sorry, I just saw this.
Thank you very much for the feedback! I am glad that you found it useful :)
I fixed both issues and added a little test to check it.

I am closing this issue – please, do let me know if you find any other problems.
Best,
F
