### ISSUE TITLE
solving with solve_ivp 

### ISSUE THREAD

**Issue by MoJaNoohi** [fabridamicelli/kuramoto#6]
Hi,
sorry I want to make some events with this code and I know that this code use ODEINT for solving differential equations.
So , I tried to change the code and solve with solve-ivp but , I'm not successful !

Can you help me that how I must change the code?
Sincerely yours,
MohammadJavad.

**Comment by fabridamicelli** [comment]
Hi,
can you please provide the code that you tried and didn't work? Having a concrete example at hand makes it much easier to figure out a solution. Thanks.

F

**Comment by MoJaNoohi** [comment]
Hello ,
I want to replace the "odeint" with "solve_ivp" because I want to make an
event that when the order parameter reaches a threshold , the program stops.

I send the code(from your library) that must be edit :
  "  def integrate(self, angles_vec, adj_mat):
        '''Updates all states by integrating state of all nodes'''
        # Coupling term (k / Mj) is constant in the integrated time window.
        # Compute it only once here and pass it to the derivative function
        n_interactions = (adj_mat != 0).sum(axis=0)  # number of incoming
interactions
        coupling = self.coupling / n_interactions  # normalize coupling by
number of interactions

        t = np.linspace(0, self.T, int(self.T/self.dt))
       * timeseries = odeint(self.derivative, angles_vec, t, args=(adj_mat,
coupling))*
        return timeseries.T  # transpose for consistency (act_mat:node vs
time)"
You know when I edit the code with " solve_ivp" the program gives me
dangerous errors.

I send a case that show the difference of "solve_ivp" and "odeint" :
https://kitchingroup.cheme.cmu.edu/blog/2018/09/04/A-new-ode-integrator-function-in-scipy/

Please help me solve the problem.
Sincerely,
MohammadJavad.

**Comment by fabridamicelli** [comment]
If your goal is just to run the simulation setting a stop threshold you can simply run smaller time windows and check after each interval if the criterion is met. I just put together [this example notebook](https://github.com/fabridamicelli/kuramoto/blob/master/examples/sync_threshold.ipynb) for quick demonstration of the idea.
I hope that (or something pretty similar) makes the job and keeps things simple. Let me know if that works.

**Comment by fabridamicelli** [comment]
@MohammadJavadNouhi I assume the proposed solution is OK, so I am closing this issue.
