### ISSUE TITLE
Chimera States in Kuramoto Model

### ISSUE THREAD

**Issue by Rumcohol** [fabridamicelli/kuramoto#7]
# I want to simulate **chimera states** (_simultaneous co-existence of synchronous and non synchronous states_). It can be achieved by doing a few changes in the Kuramoto model. We can **introduce a phase lag** in one of the oscillators in the network. Another possible way to do so is , instead of using a symmetric global coupling if we use **an asymmetric or directional matrix** (Kij != Kji) Chimera can be observed. I tried it for 4 oscillators with ode_int and it worked fine.

from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt

def odes(x, t):
    #constants
    a1 = 10
    a2 = 10
    a3 = 10
    a4 = 10
    d=np.pi/6

    #assign each ODE to a vector element
    A = x[0]
    B = x[1]
    C = x[2]
    D = x[3]

    #define each ODE
    dAdt = a1 -5*(np.sin(A-B)+np.sin(A-C)+np.sin(A-D))
    dBdt = a2 -5*(np.sin(B-C)+np.sin(B-C)+np.sin(B-D))
    dCdt =  a3 -5*(np.sin(C-A)+np.sin(C-B)+np.sin(C-D))
    dDdt =  a4 -9*(np.sin(D-A-d)+np.sin(D-B-d)+np.sin(D-C-d)) #introducing a delay in one oscillator

    return [dAdt, dBdt, dCdt,dDdt]

#initial conditions
x0 = [0.1, 2, 0.9,1]

#test the defined odes
#print(odes(x=x0,t=0))

#declare a time vector (time window)
t = np.linspace(0,2,10000)
x = odeint(odes,x0,t)

A = x[:,0]
B = x[:,1]
C = x[:,2]
D = x[:,3]

#plot the results
plt.plot(t,A)
plt.plot(t,B)
plt.plot(t,C)
plt.plot(t,D)
plt.show()

# **But for 'n' oscillators I'm not able to simulate it properly.**

from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt
n= 50
summ=np.zeros((1000,n))
dAdt=np.zeros((1000,n))

def odes(x, t):
    
 
  

    A=np.zeros((1000,n))
    for i in range(n):
        A[i] = x[i]
        for j in range (0):
            summ[i]=np.sum(np.sin(x[i]-x[j])) #
        dAdt[i] = 10*(i+1) -5*summ[i]
            
        return dAdt[i]
        
x0 = [0.1, 0.6, 0.9,1]

t = np.linspace(0,5,1000)
x = odeint(odes,x0,t)

A = x[:,0]
B = x[:,1]
C = x[:,2]
D = x[:,3]

#plot the results
plt.plot(t,A)
plt.plot(t,B)
plt.plot(t,C)
plt.plot(t,D)
plt.show()

print(A)

I would really appreciate the suggestions on my code.

**Comment by fabridamicelli** [comment]
Hi @Rumcohol 

I just pushed a new release (version 0.3.0) that you can directly pip install.
The symmetry constraint was removed, so now you can use an asymmetric connectivity matrix.
The constraint wasn't actually necessary anymore because in any case only the incoming neighbors affect the dynamics of each node.
 There is a jupyter notebook with an example [here](https://github.com/fabridamicelli/kuramoto/blob/master/examples/readme_example_asymmetric.ipynb)

Please do let me know if that works for you now or if you notice any problems =)
F

**Comment by fabridamicelli** [comment]
Hi @Rumcohol 
if you don't have any further comments/issues with this topic I will just close this issue soon.
F

**Comment by Rumcohol** [comment]
Thanks for the update . The asymmetric matrix works fine.  The issue is resolved.
