### ISSUE TITLE
Predicting time sequences

### ISSUE THREAD

**Issue by SutirthaChakraborty** [fabridamicelli/kuramoto#9]
Is there any possibility of using the package to predict phase time? I have a list containing the phase time in milliseconds to predict the following few phase timing. 
`[  66.37777778, 962.47777778, 1028.85555556, 1227.98888889, 1427.12222222, 1493.5  ,1924.95555556, 1991.33333333 2389.6 ,2455.97777778, 2953.92222222, 3020.3, 3418.56666667, 3518.13333333]`

I want to get the subsequent few intervals using Kuramoto's equation to Sync.

**Comment by fabridamicelli** [comment]
Hi,
I am afraid your question has too little information for me to understand what your goal/problem is.
If you could provide some more details maybe I could help (like a bit of the context of the problem, the code you used to generate that sequence of values, any code that you wrote to try to achieve the mentioned goal, etc)

**Comment by SutirthaChakraborty** [comment]
Thanks, I have a  [video](https://drive.google.com/uc?id=19dp0f9JyJa2cbQet2rMw54e2pGwujKGG), where I move my arms at a specific BPM.  I generated a graph using the body key points and generated a graph and detected the peaks. 
![image](https://user-images.githubusercontent.com/47362033/205279576-7169eafc-0d0d-44ed-8efa-efa8053ba87f.png)
I consider the peak times as a phase,  I created a small buffer for 4 seconds. I want the Kuramoto model to synchronize with the frame and predict the subsequent successive phases. 

Here is the [Colab](https://colab.research.google.com/drive/1UTdr00w1p2TCqb9yAchYCwlBCIk5o9vL?usp=sharing)

**Comment by fabridamicelli** [comment]
I am still not sure I understand the problem statement.
What I get so far is:  you have a bunch of time series, one for each part of the body (what you call "key points"). Your goal is to model those time series with the kuramoto model? That is, you assume there is some synchronization between the body parts going on and you want to capture that with the kuramoto equations?

I still don't understand why you "I consider the peak times as a phase"?
What is this plot representing?

**Comment by SutirthaChakraborty** [comment]
Yes you are right. The time difference between between two peaks is one phase. I want to design a second oscillator, which would try to sync with the human body movements.

**Comment by fabridamicelli** [comment]
I don't understand why you choose to model this with the kuramoto model. 
Is your goal to have a predictive model that can reproduce your signal?

**Comment by SutirthaChakraborty** [comment]
In case of change in speed of motion, I want it to be more like a slow and steady state change rather than using time series prediction. Yes. I want to reproduce a signal which would be adaptive to the change of the signal.
